id: I43747247
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:13:47.854007'
last_modified: '2022-06-18T20:13:47.854021'
parser: null
source_metadata:
  title: Reply to criticisms of the Kālacakra (Old block print), colophon excerpt
  author: འགོས་ལོ་ཙཱ་བ་གཞོན་ནུ་དཔལ།
  description: 'Digital version 1.0 {Tibetan}, diplomatic edition of witness A; master
    xml (completed: 2020-05-26); revised, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:-
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/2120
  bases:
    b0b2:
      title: Reply to criticisms of the Kālacakra (Old block print), colophon excerpt
      order: 1
      base_file: b0b2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
